### ISSUE TITLE
uninitialized constant Module::Socket

### ISSUE THREAD

**Issue by parshap** [stephencelis/ghi#177]
I get this exception after doing `ghi config --auth`.

```
$ ruby --version           
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-linux-gnu]

$ ghi --version
ghi version 0.9.3

$ ghi config --auth parshap                                                                                                                                             
Enter parshap's GitHub password (never stored): /var/lib/gems/2.1.0/gems/ghi-0.9.3/lib/ghi/authorization.rb:23:in `authorize!': uninitialized constant Module::Socket (NameError)
        from /var/lib/gems/2.1.0/gems/ghi-0.9.3/lib/ghi/commands/config.rb:27:in `execute'
        from /var/lib/gems/2.1.0/gems/ghi-0.9.3/lib/ghi/commands/command.rb:17:in `execute'
        from /var/lib/gems/2.1.0/gems/ghi-0.9.3/lib/ghi.rb:80:in `execute'
        from /var/lib/gems/2.1.0/gems/ghi-0.9.3/bin/ghi:4:in `<top (required)>'
        from /usr/local/bin/ghi:23:in `load'
        from /usr/local/bin/ghi:23:in `<main>'
```

**Comment by wjdp** [comment]
Seems the rubygems current version still has this bug, the github master does not
