### ISSUE TITLE
Error when authenticating

### ISSUE THREAD

**Issue by stepthom** [stephencelis/ghi#178]
I've just installed ghi and am receiving an error when running `ghi config`:

```
[dev@ubuntu:/dataware/tools (develop)] $ ghi list
# datawareventures/tools open issues
Authorization required.

Please run 'ghi config --auth <username>'

[dev@ubuntu:/dataware/tools (develop)] $ ghi config --auth stepthom
Enter stepthom's GitHub password (never stored): /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/authorization.rb:23:in `authorize!': uninitialized constant Module::Socket (NameError)
	from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/commands/config.rb:27:in `execute'
	from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/commands/command.rb:17:in `execute'
	from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi.rb:80:in `execute'
	from /var/lib/gems/1.8/gems/ghi-0.9.3/bin/ghi:4
	from /usr/local/bin/ghi:23:in `load'
	from /usr/local/bin/ghi:23
```

Any ideas?

**Comment by AlexChesters** [comment]
This should have been fixed now. Please reopen if you encounter this issue again in the future.
