### ISSUE TITLE
NoMethodError when running unassign

### ISSUE THREAD

**Issue by davejamesmiller** [stephencelis/ghi#182]
```
$ ghi unassign 4
/var/lib/gems/1.9.1/gems/ghi-0.9.3/lib/ghi/commands/assign.rb:39:in `execute': undefined method `sub!' for nil:NilClass (NoMethodError)
   from /var/lib/gems/1.9.1/gems/ghi-0.9.3/lib/ghi/commands/command.rb:17:in `execute'
   from /var/lib/gems/1.9.1/gems/ghi-0.9.3/lib/ghi.rb:80:in `execute'
   from /var/lib/gems/1.9.1/gems/ghi-0.9.3/bin/ghi:4:in `<top (required)>'
   from /usr/local/bin/ghi:23:in `load'
   from /usr/local/bin/ghi:23:in `<main>'
```

The line at fault is:

```ruby
assigns[:assignee].sub! /^@/, ''
```

Since `assigns[:assignee] = nil` (line 18).

(As a workaround it's also possible to use `ghi assign 4 ""` to unassign an issue.)

**Comment by AlexChesters** [comment]
This issue has been resolved as of 257375e12af74b9ac5227c05f413827ee2a15f8c
