### ISSUE TITLE
ghi close RegexpError

### ISSUE THREAD

**Issue by andresriancho** [stephencelis/ghi#184]
```console
andres@foosa ~/pch/w3af $ ghi close 3237
/var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/formatting.rb:457:in `format_markdown': undefined (?...) sequence: /(?<indent>^\ {0})(```)\s*(?<lang>\w*$)(\n)(?<code>.+?)(\n)(^\ {0}```$)/ (RegexpError)
	from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/formatting.rb:100:in `indent'
	from (erb):1:in `format_issue'
	from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/formatting/colors.rb:47:in `no_color'
	from (erb):1:in `format_issue'
	from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/formatting/colors.rb:230:in `escape'
	from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/formatting/colors.rb:25:in `bright'
	from (erb):1:in `format_issue'
	from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/formatting.rb:207:in `format_issue'
	from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/commands/edit.rb:94:in `execute'
	from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/commands/command.rb:17:in `execute'
	from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/commands/close.rb:40:in `execute'
	from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/commands/command.rb:17:in `execute'
	from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi.rb:80:in `execute'
	from /var/lib/gems/1.8/gems/ghi-0.9.3/bin/ghi:4
	from /usr/local/bin/ghi:19:in `load'
	from /usr/local/bin/ghi:19
andres@foosa ~/pch/w3af $
```
The issue is actually closed, but I see the traceback.

**Comment by AlexChesters** [comment]
Hi @andresriancho,

What verion of Ruby are you using?

**Comment by AlexChesters** [comment]
Closing this as it's had no activity for a while. Please comment if this is still an issue. Thanks!
