### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by ThierryBegin** [stephencelis/ghi#209]
```
C:\Users\Thierry>ghi config --auth ThierryBegin
Enter ThierryBegin's GitHub password (never stored): C:/Ruby21/lib/ruby/gems/2.1
.0/gems/ghi-0.9.3/lib/ghi/commands/config.rb:51:in `ensure in get_password': und
efined method `empty?' for nil:NilClass (NoMethodError)
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/ghi-0.9.3/lib/ghi/commands/confi
g.rb:51:in `get_password'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/ghi-0.9.3/lib/ghi/commands/confi
g.rb:26:in `execute'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/ghi-0.9.3/lib/ghi/commands/comma
nd.rb:17:in `execute'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/ghi-0.9.3/lib/ghi.rb:80:in `exec
ute'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/ghi-0.9.3/bin/ghi:4:in `<top (re
quired)>'
        from C:/Ruby21/bin/ghi:23:in `load'
        from C:/Ruby21/bin/ghi:23:in `<main>'
```

**Comment by AlexChesters** [comment]
Hi @ThierryBegin,

Is this issue still occurring?

**Comment by AlexChesters** [comment]
Closing this as it's had no activity for a while. Please comment if this is still an issue. Thanks!
