### ISSUE TITLE
Build failure OS X 10.10.2 ruby 2.0.0p481.

### ISSUE THREAD

**Issue by Phrohdoh** [stephencelis/ghi#230]
```
$ rake --trace

rake aborted!
Don't know how to build task 'default'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task_manager.rb:49:in `[]'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:142:in `invoke_task'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:101:in `block (2 levels) in top_level'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:101:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:101:in `block in top_level'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:110:in `run_with_threads'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:95:in `top_level'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:73:in `block in run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:70:in `run'
/usr/bin/rake:37:in `<main>'
```

**Comment by AlexChesters** [comment]
Hi,

This isn't an issue. If you look at the [Rakefile](https://github.com/stephencelis/ghi/blob/master/Rakefile) you'll see that the available tasks are `build`, `man`, and `install`.
