### ISSUE TITLE
Error on show, edit

### ISSUE THREAD

**Issue by gleachkr** [stephencelis/ghi#257]
I'm encountering the following error on `ghi show 1`:

```
/usr/local/bin/ghi:4235:in `pull_request?': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/bin/ghi:4218:in `execute'
	from /usr/local/bin/ghi:2762:in `execute'
	from /usr/local/bin/ghi:91:in `execute'
	from /usr/local/bin/ghi:4282:in `<main>'
```

`ghi show -w 1` works fine, as does `ghi list`. `ghi edit 1` gives 

```
(erb):1:in `format_issue': undefined method `[]' for nil:NilClass (NoMethodError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `eval'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `result'
	from /usr/local/bin/ghi:2058:in `format_issue'
	from (erb):10:in `block in format_editor'
	from /usr/local/bin/ghi:1531:in `no_color'
	from (erb):10:in `format_editor'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `eval'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `result'
	from /usr/local/bin/ghi:2213:in `format_editor'
	from /usr/local/bin/ghi:3282:in `execute'
	from /usr/local/bin/ghi:2762:in `execute'
	from /usr/local/bin/ghi:91:in `execute'
	from /usr/local/bin/ghi:4282:in `<main>'
```

It's probably just something I've got misconfigured, but if you've got any insights on what the trouble might be, that'd be helpful. Running OS X 10.10

**Comment by AlexChesters** [comment]
Hi @gleachkr,

Thanks for reporting this. Can you provide the url for the repo you are using (if it's a public one)?

**Comment by gleachkr** [comment]
Sure, the repo is https://github.com/gleachkr/Carnap

**Comment by AlexChesters** [comment]
@gleachkr I can't reproduce it. What version of `ghi` are you running?

`ghi -v`

**Comment by gleachkr** [comment]
1.0.3

**Comment by gleachkr** [comment]
Fixed it. The trouble was that I had changed the name of the repository on github. So `git config --get remote.origin.url` was locally returning the old repository name. Updating the config resolved the issue.

**Comment by AlexChesters** [comment]
Ahh glad to hear its sorted! :smile:
