### ISSUE TITLE
ghi show -p: bad URI

### ISSUE THREAD

**Issue by jamietanna** [stephencelis/ghi#296]
When running `ghi show -p` in a repo, I receive the error `bad URI`. The full error is as follows:

```
$ ghi show -p 30
/usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:18:in `rescue in split': bad URI(is not URI?):  (URI::InvalidURIError)
        from /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:15:in `split'
        from /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
        from /usr/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
        from /home/jamie/workspaces/tmp/ghi/ghi:1434:in `curl'
        from /home/jamie/workspaces/tmp/ghi/ghi:2932:in `block in execute'
        from /home/jamie/workspaces/tmp/ghi/ghi:1056:in `throb'
        from /home/jamie/workspaces/tmp/ghi/ghi:2932:in `execute'
        from /home/jamie/workspaces/tmp/ghi/ghi:1473:in `execute'
        from /home/jamie/workspaces/tmp/ghi/ghi:94:in `execute'
        from /home/jamie/workspaces/tmp/ghi/ghi:3007:in `<main>'
```

The remote for the repo is `git@github.com:jamietanna/dotfiles-arch`.

**Comment by shubhamshuklaer** [comment]
Sorry It was caused by my commit(22a39f6). I have created a pull request fixing it. Try https://github.com/shubhamshuklaer/ghi/blob/check_if_proxy_nil/ghi , and commit whether it works.

**Comment by jamietanna** [comment]
@shubhamshuklaer I can confirm that the code as of <https://github.com/shubhamshuklaer/ghi/blob/check_if_proxy_nil/ghi> works correctly.
