### ISSUE TITLE
Crash when viewing issue from mypy

### ISSUE THREAD

**Issue by refi64** [stephencelis/ghi#325]
Inside [this repo](https://github.com/python/mypy):

```
ryan@DevPC-LX /media/ryan/stuff/mypy master $ ghi 2373
/var/lib/gems/1.9.1/gems/ghi-1.2.0/lib/ghi/commands/show.rb:52:in `pull_request?': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/gems/1.9.1/gems/ghi-1.2.0/lib/ghi/commands/show.rb:35:in `execute'
	from /var/lib/gems/1.9.1/gems/ghi-1.2.0/lib/ghi/commands/command.rb:17:in `execute'
	from /var/lib/gems/1.9.1/gems/ghi-1.2.0/lib/ghi.rb:80:in `execute'
	from /var/lib/gems/1.9.1/gems/ghi-1.2.0/bin/ghi:4:in `<top (required)>'
	from /usr/local/bin/ghi:23:in `load'
	from /usr/local/bin/ghi:23:in `<main>'
ryan@DevPC-LX /media/ryan/stuff/mypy master $ 
```

**Comment by lsloan** [comment]
The equivalent command, without cloning that repo ([python/mypy](/python/mypy)) locally, would be:

```bash
ghi 2373 -- python/mypy
``` 

When I run that command, it produces the following output (the contents of python/mypy#2373), which appears to be correct:

> ```txt
> #2373: Disallow isinstance of generic expressions
> @ddfisher opened this issue 108 days ago.   open  (3 comments)
>  bug   priority-1-normal
> Milestone #6: 0.5
> 
>     Now that runtime generics are allowed (thanks to #2302), we should prevent
>     people from making calls like:
> ```
> 
Etc.

* Is it agreed that this form of the command is equivalent?
* Can others reproduce the problem reported?
