### ISSUE TITLE
Ghi fails to operate correctly on windows 10 powershell

### ISSUE THREAD

**Issue by AidaPaul** [stephencelis/ghi#372]
I did a fresh install of latest rubyinstaller and after gem-installing GHI this is what I see in powershell:

```Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> ghi
fatal: --local can only be used inside a git repository
Traceback (most recent call last):
        12: from C:/Ruby25-x64/bin/ghi:23:in `<main>'
        11: from C:/Ruby25-x64/bin/ghi:23:in `load'
        10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/bin/ghi:4:in `<top (required)>'
         9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/lib/ghi.rb:80:in `execute'
         8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/lib/ghi/commands/command.rb:17:in `execute'
         7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/lib/ghi/commands/list.rb:143:in `execute'
         6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/lib/ghi/formatting.rb:167:in `format_issues_header'
         5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/lib/ghi/formatting.rb:337:in `format_state'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/lib/ghi/formatting/colors.rb:17:in `fg'
         3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/lib/ghi/formatting/colors.rb:228:in `escape'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/lib/ghi/formatting/colors.rb:236:in `escape_256'
         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/lib/ghi/formatting/colors.rb:240:in `supports_256_colors?'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/lib/ghi/formatting/colors.rb:240:in ``': No such file or directory - tput colors (Errno::ENOENT)
```
Same if I try any other commands, which makes the interactive one return back to console:

```PS C:\Windows\system32> ghi config -auth xxxx@gmail.com
Enter uth's GitHub password (never stored): Traceback (most recent call last):
        7: from C:/Ruby25-x64/bin/ghi:23:in `<main>'
        6: from C:/Ruby25-x64/bin/ghi:23:in `load'
        5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/bin/ghi:4:in `<top (required)>'
        4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/lib/ghi.rb:80:in `execute'
        3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/lib/ghi/commands/command.rb:17:in `execute'
        2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/lib/ghi/commands/config.rb:28:in `execute'
        1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/lib/ghi/commands/config.rb:53:in `get_password'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ghi-1.2.0/lib/ghi/commands/config.rb:53:in `ensure in get_password': undefined method `empty?' for nil:NilClass (NoMethodError)
```

I did another fresh install of ruby, making sure it's pristine and nothing else is messing it up or system patches but also to no avail. Any ideas how to fix it?

UPDATE: same happens in cmd.exe

**Comment by harbertc** [comment]
I also experience the above behavior.
