### ISSUE TITLE
ghi can't show issues(EOFerror)

### ISSUE THREAD

**Issue by eval-exec** [stephencelis/ghi#379]
```
$ ghi list
# slarsar/leetcode_solutions open issues
Traceback (most recent call last):
        15: from /usr/bin/ghi:3157:in `<main>'
        14: from /usr/bin/ghi:94:in `execute'
        13: from /usr/bin/ghi:1526:in `execute'
        12: from /usr/bin/ghi:2602:in `execute'
        11: from /usr/bin/ghi:1105:in `throb'
        10: from /usr/bin/ghi:2604:in `block in execute'
         9: from /usr/bin/ghi:1337:in `get'
         8: from /usr/bin/ghi:1392:in `request'
         7: from /usr/lib/ruby/2.6.0/net/http.rb:919:in `start'
         6: from /usr/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
         5: from /usr/lib/ruby/2.6.0/net/http.rb:969:in `connect'
         4: from /usr/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'
         3: from /usr/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
         2: from /usr/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
         1: from /usr/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
/usr/lib/ruby/2.6.0/net/protocol.rb:225:in `rbuf_fill': end of file reached (EOFError)

```

**Comment by eval-exec** [comment]
```
$  uname -a               
Linux mufasa 5.2.14-arch1-1-ARCH #1 SMP PREEMPT Tue Sep 10 18:11:49 UTC 2019 x86_64 GNU/Linux

```

**Comment by eval-exec** [comment]
```
$  locale   
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

```

**Comment by eval-exec** [comment]
where is the ghi log can I provide?
